### ISSUE TITLE
Failing test "testStrNWeekDay"

### ISSUE THREAD

**Issue by nvartolomei** [jakubroztocil/rrule#136]
This one fails for me:

```
1) rrulestr testStrNWeekDay [every year on the 1st Tuesday and last Thursday for 3 times] [FREQ=YEARLY;COUNT=3;BYDAY=+1TU,-1TH;DTSTART=19970902T090000Z]:

      AssertionError:  - 1/3
      + expected - actual

      -Thu Dec 25 1997 11:00:00 GMT+0200 (EET)
      +Thu Dec 25 1997 12:00:00 GMT+0200 (EET)

      at assertDatesEqual (test/lib/utils.js:20:12)
      at Context.<anonymous> (test/lib/utils.js:103:5)
```

**Comment by davidgoli** [comment]
This is currently enabled and passing.
