### ISSUE TITLE
Unsupported RFC prop EXDATE in EXDATE;TZID=America/New_York:20180921T130000

### ISSUE THREAD

**Issue by agordeev** [jakubroztocil/rrule#335]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.

The lib is unable to parse this rule:

```
[ 'DTSTART:20180323T170000Z',
  'EXDATE;TZID=America/New_York:20180921T130000',
  'RRULE:FREQ=WEEKLY;UNTIL=20190208T045959Z;INTERVAL=2;BYDAY=FR' ]
```

The error is: 

```
error: Unable to generate daily stats. Transaction failed. Error: Unsupported RFC prop EXDATE in EXDATE;TZID=America/New_York:20180921T130000
    at parseLine (/xxx/functions/node_modules/rrule/dist/es5/rrule.js:1004:19)
    at Array.map (<anonymous>)
    at Function.parseString (/xxx/functions/node_modules/rrule/dist/es5/rrule.js:972:41)
    at Function.RRule.fromString (/xxx/functions/node_modules/rrule/dist/es5/rrule.js:2006:32)
    at RecurrenceWorker.getRRule (/xxx/functions/lib/src/algorithm/workers/recurrenceWorker.js:81:40)
    at RecurrenceWorker.between (/xxx/functions/lib/src/algorithm/workers/recurrenceWorker.js:20:29)
    at RecurrenceWorker.getStartEndArrayFromRecurrence (/xxx/functions/lib/src/algorithm/workers/recurrenceWorker.js:52:29)
    at AvailableTimeForTasksWorker.calculateMinutesTakenByRecurringEvent (/xxx/functions/lib/src/stats/workers/availableTimeForTasksWorker.js:170:60)
    at AvailableTimeForTasksWorker.<anonymous> (/xxx/functions/lib/src/stats/workers/availableTimeForTasksWorker.js:67:43)
    at Generator.next (<anonymous>)
```

- [x] The version of `rrule` you are using: **2.6.0**
- [x] Your operating system: no idea, the code is executed by Google Firebase

Isn't EXDATE string valid? It comes from Google Calendar

**Comment by davidgoli** [comment]
It's not valid in the RFC for EXDATE to have a different TZID from DTSTART. However, it should still parse.

You should use this with `rrulestr` as follows:

```ts
rrulestr(
      [ 'DTSTART:20180323T170000Z',
  'EXDATE;TZID=America/New_York:20180921T130000',
  'RRULE:FREQ=WEEKLY;UNTIL=20190208T045959Z;INTERVAL=2;BYDAY=FR' ].join('\n')
    )
```

**Comment by titanism** [comment]
Also investigating and seeing this error from `EXDATE;TZID=W`:

```sh
rrulestr(['DTSTART:20180323T170000Z', 'EXDATE;TZID=W', 'RRULE:FREQ=WEEKLY;UNTIL=20190208T045959Z;INTERVAL=2;BYDAY=FR'].join('\n'));
Uncaught Error: Unsupported RFC prop EXDATE in EXDATE;TZID=W
```

**Comment by titanism** [comment]
Our fix is implemented at <https://github.com/forwardemail/forwardemail.net/commit/5f296a17a3ae057a1e02e5cc60132614218cede2>, it seems some clients sent over an invalid EXDATE value without a time/date included, so we check if it's valid, and if not, exclude it.
