### ISSUE TITLE
`rdate` not working with 2.6.4 with example code

### ISSUE THREAD

**Issue by cmmash** [jakubroztocil/rrule#396]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output - occurrences as according to the rruleset
- [x] Actual output - error
- [x] The version of `rrule` you are using - 2.6.4
- [x] Your operating system - Ubuntu 18.04.3 LTS
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug) - IST (India)

Taking the example code as given in docs:

```javascript
const { RRule, RRuleSet, rrulestr } = require('rrule');


const rruleSet = new RRuleSet()

// Add a rrule to rruleSet
rruleSet.rrule(new RRule({
  freq: RRule.MONTHLY,
  count: 5,
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30))
}))

// Add a date to rruleSet
rruleSet.rdate(new Date(Date.UTC(2012, 6, 1, 10, 30)))
```

This gives the following error:

```javascript
> rruleSet.rdate(new Date(Date.UTC(2012, 6, 1, 10, 30)))
TypeError: Sun Jul 01 2012 16:00:00 GMT+0530 (India Standard Time) is not Date instance
    at _addDate (/tmp/try-package-aVbBff/node_modules/rrule/dist/es5/rrule.js:2709:15)
    at RRuleSet.rdate (/tmp/try-package-aVbBff/node_modules/rrule/dist/es5/rrule.js:2613:9)
> 
```

I had tried it out with `npm-try rrule@2.6.4`

**Comment by cmmash** [comment]
NVM, it was some `npm-try` problem only probably, as I tried out the example in a standalone node app, and it works fine.

**Comment by cmmash** [comment]
For anyone else wanting to try out `rrule` quickly in a nodejs environment, you can give https://github.com/cmmash/rrule-demo a try.
