### ISSUE TITLE
TZID requires luxon warning, when I have Luxon already 

### ISSUE THREAD

**Issue by mapidemic** [jakubroztocil/rrule#427]
- [ ] Code sample reproducing the issue. Be sure to include all input values you
See https://stackoverflow.com/questions/64299310/rrule-using-tzid-without-luxon-available-is-unsupported for issue details

- [ ] Expected output
No warnings

- [ ] Actual output
Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone

- [ ] The version of `rrule` you are using
Latest

- [ ] Your operating system
Ubuntu 18.04

- [ ] Your local timezone
Europe/London

**Comment by neekey** [comment]
I think this issue starts with 2.6.6? It should not just be a warning, should just throw an error, and in a real application, replace the timezone with UTC will cause serious business issues (in my case I'm writing a medical appointment system, this change caused all the appointments having wrong start time).

**Comment by neekey** [comment]
I can confirm roll back to `2.6.4` fixed this issue. and I think there are two main issues about this new version update:

- 1. as I mentioned in my previous comment, it's quite a big breaking change, it shouldn't just be a minor version increase, I used `^2.6.4` in my package.json, ended up upgrading it to `2.6.6` while I was refreshing the package-lock.json for other reasons.
- 2. even with the warning, it's not clear how to "provide luxon", nowhere in this repo mentioned that.

**Comment by marcoancona** [comment]
I confirm the issue. Luxon is never found in 2.6.6 and a warning is displayed.

**Comment by jkassis** [comment]
i am doing a rollup that includes the rrule library and am getting this...

```
Error: 'DateTime' is not exported by apps/store/code/node_modules/luxon/build/cjs-browser/luxon.js, imported by apps/store/code/node_modules/rrule/dist/esm/src/datewithzone.js
    at error (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:5156:30)
    at Module.error (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:9659:16)
    at handleMissingExport (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:9581:28)
    at Module.traceVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:10054:24)
    at ModuleScope.findVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:8613:39)
    at FunctionScope.findVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:2683:38)
    at ChildScope.findVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:2683:38)
    at FunctionScope.findVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:2683:38)
    at ChildScope.findVariable (file:///Users/jkassis/Code/merchie/server/node_modules/rollup/dist/es/shared/rollup.js:2683:38)
```

**Comment by jkassis** [comment]
https://github.com/moment/luxon/issues/252

and

https://github.com/moment/luxon/issues/591

**Comment by jkassis** [comment]
`yarn add --ignore-optional rrule` does not seem to work. i'll try a custom build without the luxon dependency. sigh.

**Comment by alexsotocx** [comment]
How do I include Luxon again? I have it on my npm modules but rrule is not working as it was 2.6.4 I get the error `Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone`

**Comment by spacegangster** [comment]
Is it viable to add a test for that? To test that Luxon plugs in.
 How costly will it be?

**Comment by lxcid** [comment]
For anyone still facing this issue, https://github.com/jakubroztocil/rrule/pull/410 is the PR of reference.

Basically, if you are using commonjs module system, you can no longer provide luxon as it automatically replaced with fake_luxon.

I would suggest anyone with this problem to stick it to 2.6.4 if possible. or you have to switch to es module system.

**Comment by hcharley** [comment]
@lxcid thank you for your advice to stick to 2.6.4.

**Comment by Melodyn** [comment]
I'm using ES modules in a Node.js backend, and on version 2.6.8 I'm getting the error "Using TZID without Luxon available is unsupported". Downgrade to version 2.6.4. didn't work either, the error persists. Is there a way to fix the error or silence it?

**Comment by davidgoli** [comment]
Luxon is no longer used as of 2.7.0
